import { getD1 } from "@/db";
import type { NeonQueryFunction } from "@neondatabase/serverless";

export type StoreClickSummary = {
  store: string;
  clicks: number;
  recentClicks: number;
  lastClickAt: string | null;
};

export type ProductClickSummary = {
  store: string;
  productId: string | null;
  productName: string;
  targetUrl: string;
  clicks: number;
  lastClickAt: string | null;
};

export type SourceClickSummary = {
  source: string;
  clicks: number;
  recentClicks: number;
  lastClickAt: string | null;
};

export type ClickMetricsOverview = {
  totalClicks: number;
  recentClicks: number;
  storeCount: number;
  productCount: number;
  lastClickAt: string | null;
};

type NeonSql = NeonQueryFunction<false, false>;

let neonSql: NeonSql | null = null;

async function getNeonSql() {
  if (!process.env.DATABASE_URL) return null;
  if (neonSql) return neonSql;

  const { neon } = await import("@neondatabase/serverless");
  neonSql = neon(process.env.DATABASE_URL);

  return neonSql;
}

const createClicksTableSql = `
CREATE TABLE IF NOT EXISTS outbound_clicks (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  store TEXT NOT NULL,
  product_id TEXT,
  product_name TEXT,
  target_url TEXT NOT NULL,
  source TEXT NOT NULL DEFAULT 'catalog',
  clicked_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
)`;

const createPostgresClicksTableSql = `
CREATE TABLE IF NOT EXISTS outbound_clicks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  store TEXT NOT NULL,
  product_id TEXT,
  product_name TEXT,
  target_url TEXT NOT NULL,
  source TEXT NOT NULL DEFAULT 'catalog',
  clicked_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
)`;

const createStoreIndexSql = "CREATE INDEX IF NOT EXISTS idx_outbound_clicks_store_clicked_at ON outbound_clicks (store, clicked_at)";
const createProductIndexSql = "CREATE INDEX IF NOT EXISTS idx_outbound_clicks_product_id ON outbound_clicks (product_id)";

export async function ensureOutboundClicksSchema() {
  const sql = await getNeonSql();
  if (sql) {
    await sql.query(createPostgresClicksTableSql);
    await sql.query(createStoreIndexSql);
    await sql.query(createProductIndexSql);
    return;
  }

  const d1 = await getD1();

  await d1.prepare(createClicksTableSql).run();
  await d1.prepare(createStoreIndexSql).run();
  await d1.prepare(createProductIndexSql).run();
}

export async function recordOutboundClick(input: {
  store: string;
  productId: string | null;
  productName: string | null;
  targetUrl: string;
  source: string;
}) {
  const sql = await getNeonSql();
  if (sql) {
    await ensureOutboundClicksSchema();
    await sql`
      INSERT INTO outbound_clicks (store, product_id, product_name, target_url, source)
      VALUES (${input.store}, ${input.productId}, ${input.productName}, ${input.targetUrl}, ${input.source})
    `;
    return;
  }

  const d1 = await getD1();

  await ensureOutboundClicksSchema();
  await d1
    .prepare(
      `INSERT INTO outbound_clicks (store, product_id, product_name, target_url, source)
       VALUES (?, ?, ?, ?, ?)`,
    )
    .bind(input.store, input.productId, input.productName, input.targetUrl, input.source)
    .run();
}

export async function getStoreClickSummaries(): Promise<StoreClickSummary[]> {
  const sql = await getNeonSql();
  if (sql) {
    await ensureOutboundClicksSchema();
    const rows = await sql`
      SELECT
        store,
        COUNT(*)::int AS clicks,
        COUNT(*) FILTER (WHERE clicked_at >= NOW() - INTERVAL '7 days')::int AS "recentClicks",
        MAX(clicked_at)::text AS "lastClickAt"
      FROM outbound_clicks
      GROUP BY store
      ORDER BY "recentClicks" DESC, clicks DESC, store ASC
    `;

    return rows as StoreClickSummary[];
  }

  const d1 = await getD1();

  await ensureOutboundClicksSchema();
  const rows = await d1
    .prepare(
      `SELECT
         store,
         COUNT(*) AS clicks,
         SUM(CASE WHEN clicked_at >= datetime('now', '-7 days') THEN 1 ELSE 0 END) AS recentClicks,
         MAX(clicked_at) AS lastClickAt
       FROM outbound_clicks
       GROUP BY store
       ORDER BY recentClicks DESC, clicks DESC, store ASC`,
    )
    .all<StoreClickSummary>();

  return rows.results;
}

export async function getSourceClickSummaries(): Promise<SourceClickSummary[]> {
  const sql = await getNeonSql();
  if (sql) {
    await ensureOutboundClicksSchema();
    const rows = await sql`
      SELECT
        source,
        COUNT(*)::int AS clicks,
        COUNT(*) FILTER (WHERE clicked_at >= NOW() - INTERVAL '7 days')::int AS "recentClicks",
        MAX(clicked_at)::text AS "lastClickAt"
      FROM outbound_clicks
      GROUP BY source
      ORDER BY "recentClicks" DESC, clicks DESC, source ASC
    `;

    return rows as SourceClickSummary[];
  }

  const d1 = await getD1();

  await ensureOutboundClicksSchema();
  const rows = await d1
    .prepare(
      `SELECT
         source,
         COUNT(*) AS clicks,
         SUM(CASE WHEN clicked_at >= datetime('now', '-7 days') THEN 1 ELSE 0 END) AS recentClicks,
         MAX(clicked_at) AS lastClickAt
       FROM outbound_clicks
       GROUP BY source
       ORDER BY recentClicks DESC, clicks DESC, source ASC`,
    )
    .all<SourceClickSummary>();

  return rows.results;
}

export async function getClickMetricsOverview(): Promise<ClickMetricsOverview> {
  const sql = await getNeonSql();
  if (sql) {
    await ensureOutboundClicksSchema();
    const rows = await sql`
      SELECT
        COUNT(*)::int AS "totalClicks",
        COUNT(*) FILTER (WHERE clicked_at >= NOW() - INTERVAL '7 days')::int AS "recentClicks",
        COUNT(DISTINCT store)::int AS "storeCount",
        COUNT(DISTINCT product_id)::int AS "productCount",
        MAX(clicked_at)::text AS "lastClickAt"
      FROM outbound_clicks
    `;

    return rows[0] as ClickMetricsOverview;
  }

  const d1 = await getD1();

  await ensureOutboundClicksSchema();
  const rows = await d1
    .prepare(
      `SELECT
         COUNT(*) AS totalClicks,
         SUM(CASE WHEN clicked_at >= datetime('now', '-7 days') THEN 1 ELSE 0 END) AS recentClicks,
         COUNT(DISTINCT store) AS storeCount,
         COUNT(DISTINCT product_id) AS productCount,
         MAX(clicked_at) AS lastClickAt
       FROM outbound_clicks`,
    )
    .all<ClickMetricsOverview>();

  return rows.results[0] ?? {
    totalClicks: 0,
    recentClicks: 0,
    storeCount: 0,
    productCount: 0,
    lastClickAt: null,
  };
}

export async function getProductClickSummaries(): Promise<ProductClickSummary[]> {
  const sql = await getNeonSql();
  if (sql) {
    await ensureOutboundClicksSchema();
    const rows = await sql`
      SELECT
        store,
        product_id AS "productId",
        COALESCE(product_name, target_url) AS "productName",
        target_url AS "targetUrl",
        COUNT(*)::int AS clicks,
        MAX(clicked_at)::text AS "lastClickAt"
      FROM outbound_clicks
      GROUP BY store, product_id, product_name, target_url
      ORDER BY clicks DESC, "lastClickAt" DESC
      LIMIT 100
    `;

    return rows as ProductClickSummary[];
  }

  const d1 = await getD1();

  await ensureOutboundClicksSchema();
  const rows = await d1
    .prepare(
      `SELECT
         store,
         product_id AS productId,
         COALESCE(product_name, target_url) AS productName,
         target_url AS targetUrl,
         COUNT(*) AS clicks,
         MAX(clicked_at) AS lastClickAt
       FROM outbound_clicks
       GROUP BY store, product_id, product_name, target_url
       ORDER BY clicks DESC, lastClickAt DESC
       LIMIT 100`,
    )
    .all<ProductClickSummary>();

  return rows.results;
}
